2023-10-31 06:24:02,681 INFO    MainThread:585 [wandb_setup.py:_flush():76] Configure stats pid to 585
2023-10-31 06:24:02,682 INFO    MainThread:585 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-31 06:24:02,682 INFO    MainThread:585 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/Uni1/wandb/settings
2023-10-31 06:24:02,682 INFO    MainThread:585 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-31 06:24:02,682 INFO    MainThread:585 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-31 06:24:02,682 INFO    MainThread:585 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-31 06:24:02,682 INFO    MainThread:585 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-10-31 06:24:02,683 INFO    MainThread:585 [wandb_init.py:_log_setup():507] Logging user logs to /content/drive/MyDrive/Uni1/wandb/run-20231031_062402-m77k3tml/logs/debug.log
2023-10-31 06:24:02,683 INFO    MainThread:585 [wandb_init.py:_log_setup():508] Logging internal logs to /content/drive/MyDrive/Uni1/wandb/run-20231031_062402-m77k3tml/logs/debug-internal.log
2023-10-31 06:24:02,683 INFO    MainThread:585 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7afa12598700>
2023-10-31 06:24:02,684 INFO    MainThread:585 [wandb_init.py:init():547] calling init triggers
2023-10-31 06:24:02,684 INFO    MainThread:585 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 5, 'batch_size': 64}
2023-10-31 06:24:02,684 INFO    MainThread:585 [wandb_init.py:init():595] starting backend
2023-10-31 06:24:02,684 INFO    MainThread:585 [wandb_init.py:init():599] setting up manager
2023-10-31 06:24:02,688 INFO    MainThread:585 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-31 06:24:02,691 INFO    MainThread:585 [wandb_init.py:init():605] backend started and connected
2023-10-31 06:24:02,700 INFO    MainThread:585 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-10-31 06:24:07,711 INFO    MainThread:585 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-31 06:24:07,711 INFO    MainThread:585 [wandb_init.py:init():695] updated telemetry
2023-10-31 06:24:07,714 INFO    MainThread:585 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-10-31 06:25:07,762 ERROR   MainThread:585 [wandb_init.py:init():758] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-31 06:25:07,781 ERROR   MainThread:585 [wandb_init.py:init():1163] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
